name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    
    steps:
    - uses: actions/checkout@v4  # 更新到v4版本
    
    - name: Setup Pages
      uses: actions/configure-pages@v4  # 更新到v4版本
    
    - name: Upload artifact
      uses: actions/upload-pages-artifact@v3  # 更新到v3版本
      with:
        path: '.'
    
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4  # 更新到v4版本
