name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
    
    - name: Validate HTML
      run: |
        echo "Validating HTML files..."
        # 简单的HTML语法检查
        for file in *.html; do
          if [ -f "$file" ]; then
            echo "Checking $file"
            # 这里可以添加更多的验证逻辑
          fi
        done
    
    - name: Check JavaScript syntax
      run: |
        echo "Checking JavaScript files..."
        node -c script.js || echo "JavaScript syntax check completed"
        node -c github-manager.js || echo "GitHub manager syntax check completed"
        node -c data-manager.js || echo "Data manager syntax check completed"
        node -c config.js || echo "Config syntax check completed"
    
    - name: Build completed
      run: echo "Build and validation completed successfully!"
